### ISSUE TITLE
403 error loading font resource from Mapbox

### ISSUE THREAD

**Issue by ciex** [LINKIWI/orion-web#10]
I am getting an error 403 (Forbidden) in the error console of Chrome and Safari when I select a user/device using the config dropdown on the top. The error occurs when trying to load this URL

`https://api.mapbox.com/fonts/v1/linkiwi/Karla%20Regular,Arial%20Unicode%20MS%20Regular/0-255.pbf?access_token=<my_token>`

I am using the default token provided by Mapbox after signing up and apart from this, the maps seem to work fine.

The error disappeared after replacing `src/resources/data/map-style.json` with a custom map style!

**Comment by LINKIWI** [comment]
Which SHA are you on? This should be fixed as of de1bc7168183e3a6bcda01be6988fdc507a3e70b

**Comment by ciex** [comment]
I am on 04b4578

**Comment by ciex** [comment]
I reverted to the old `map-style.json` and the error came back.

**Comment by LINKIWI** [comment]
Ah, there are still some [remaining references](https://github.com/LINKIWI/orion-web/blob/04b45782c4810ffa0acbb09e957fea975cff871c/src/resources/data/map-style.json#L7508) to the custom font. The data file was generated from Mapbox Studio so this error is difficult to catch.

I will patch this shortly

**Comment by LINKIWI** [comment]
Can you try reproducing the error on d6d699fc680418b940e1a9086e565e16d2ff6056 or alter?

**Comment by ciex** [comment]
It's fixed now. 👍
